///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String constantsAppwriteConstants =
      'lib/constants/appwrite_constants.dart';
  static const String constantsContants = 'lib/constants/contants.dart';
  static const String generatedAssets = 'lib/generated/assets_constants.dart';
  static const String iconsCorpse = 'lib/assets/icons/corpse.png';
  static const String iconsCyberSecurity =
      'lib/assets/icons/cyber-security.png';
  static const String iconsEmblem = 'lib/assets/icons/emblem.png';
  static const String iconsFingerprint = 'lib/assets/icons/fingerprint.png';
  static const String iconsForensicScience =
      'lib/assets/icons/forensic-science.png';
  static const String iconsForensics = 'lib/assets/icons/forensics.png';
  static const String iconsGlobeGrid = 'lib/assets/icons/globe-grid.png';
  static const String iconsHack = 'lib/assets/icons/hack.png';
  static const String iconsMicroscope = 'lib/assets/icons/microscope.png';
  static const String iconsNfsuLogo = 'lib/assets/icons/nfsuLogo.png';
  static const String iconsPhotographer = 'lib/assets/icons/photographer.png';
  static const String libMain = 'lib/main.dart';
}
